name: flutterstudy_weatherapp
description: Project for portifolio using API.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  http: ^1.1.0
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
